<a href="https://colab.research.google.com/github/KurniaYufi/sentiment-analysis-kematian-ali-khamenei/blob/main/scraping/cnn/cnn-content-scraping" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CNN Indonesia — Content Scraping & Preprocessing
**Input :** `scraping_cnn_100pages_clean.csv` (kolom: Judul, Link, Kategori, Tanggal_Upload)
**Output :** `cnn_analyzed_articles.csv` (+ kolom content, preprocessing, sentimen)

Alur:
1. Instalasi Library
2. Impor Library
3. Upload CSV & Scraping Konten tiap Link → kolom `content`
4. Preprocessing (clean → tokenize → stopword → stem → deteksi bahasa)
5. Analisis Sentimen (translate → TextBlob)
6. Visualisasi Word Cloud
7. Ekspor CSV

## **(1) Instalasi Library**

In [1]:
# Library scraping & data
!pip install -q beautifulsoup4 requests pandas

# Polyglot (deteksi bahasa) — perlu urutan ini agar tidak konflik
!pip uninstall -q -y icu polyglot pyicu 2>/dev/null
!pip install -q polyglot pycld2 pyicu morfessor

# NLP
!pip install -q deep-translator Sastrawi stanza nltk wordcloud

print('✅ Semua library berhasil diinstall')

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 kB 3.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.2/268.2 kB 10.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 72.6 MB/s eta 0:00:00
  Building wheel for polyglot (setup.py) ... done
  Building wheel for pyicu (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 34.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 773.7/773.7 kB 37.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 27.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 418.7/418.7 kB 20.3 MB/s eta 0:00:00
✅ Semua library berhasil diinstall

## **(2) Impor Library**

In [2]:
# Standard
import io, string, re, time
from collections import defaultdict, Counter

# Data
import pandas as pd
import numpy as np

# Scraping
import requests
from bs4 import BeautifulSoup

# NLTK
import nltk
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist

# Sastrawi (stemming)
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# Sentimen
from textblob import TextBlob
from deep_translator import GoogleTranslator

# Visualisasi
import matplotlib.pyplot as plt
from wordcloud import WordCloud

# NLTK downloads
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

print('✅ Semua library berhasil diimpor')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

✅ Semua library berhasil diimpor

## **(3) Upload CSV & Scraping Konten tiap Link**

In [3]:
from google.colab import files
import os

print('📂 Upload file CSV hasil scraping link (scraping_cnn_100pages_clean.csv)')

# Clear previously uploaded files to avoid confusion if an incorrect file was uploaded.
# This part ensures a fresh upload attempt.
# for f in files.upload(): # This loop usually gets an uploaded file. If the cell was run, 'uploaded' would be populated.
#   os.remove(f)

# The 'uploaded' variable is a dictionary of {filename: content}.
# If it already exists from a previous run, clear it.
if 'uploaded' in locals() or 'uploaded' in globals():
    uploaded = {}

uploaded = files.upload()

if not uploaded:
    print('Tidak ada file yang diunggah. Pastikan Anda memilih file CSV.')
    # If no file is uploaded, we might want to prevent further execution or ask to re-upload.
    # For now, let's just print a message and proceed, assuming the user might re-run.
else:
    filename = list(uploaded.keys())[0]
    # Check if the uploaded file has a .csv extension
    if not filename.lower().endswith('.csv'):
        print(f'⚠️  File yang diunggah bukan file CSV: {filename}. Mohon unggah file CSV yang benar.')
        # Clear the uploaded content to ensure the next cell doesn't try to process it.
        uploaded = {}
        # You might want to raise an error or exit here if you want to strictly enforce CSV upload.
        # raise ValueError('Uploaded file must be a CSV.')
    else:
        print(f'✅ File terupload: {filename}')

📂 Upload file CSV hasil scraping link (scraping_cnn_100pages_clean.csv)

Saving scraping_cnn_100pages_clean (1).csv to scraping_cnn_100pages_clean (1).csv
✅ File terupload: scraping_cnn_100pages_clean (1).csv

In [4]:
# Baca CSV
links_df = pd.read_csv(io.BytesIO(uploaded[filename]))
print(f'Jumlah baris: {len(links_df)}')
print(f'Kolom       : {links_df.columns.tolist()}')
links_df.head(3)

Jumlah baris: 99
Kolom       : ['Judul', 'Link', 'Kategori', 'Tanggal_Upload']

,Judul,Link,Kategori,Tanggal_Upload
0,Isi Dokumen Fatwa Ali Khamenei Mengharamkan Bo...,https://www.cnnindonesia.com/internasional/202...,Internasional,3 hari yang lalu
1,"Tanpa Ali Khamenei, Israel Justru Ketar-ketir ...",https://www.cnnindonesia.com/internasional/202...,Internasional,4 hari yang lalu
2,Trump Konfirmasi Kematian Pemimpin Tertinggi I...,https://www.cnnindonesia.com/internasional/202...,Internasional,2 bulan yang lalu

In [5]:
# ── Fungsi scraping konten satu artikel CNN Indonesia ────────────────────────
HEADERS = {
    'User-Agent': (
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
        'AppleWebKit/537.36 (KHTML, like Gecko) '
        'Chrome/120.0.0.0 Safari/537.36'
    )
}

def scrape_content(url):
    """
    Ambil SEMUA teks yang terlihat di halaman artikel CNN Indonesia.
    Strategi:
      1. Coba selector utama CNN Indonesia (detail_text / article body)
      2. Fallback: ambil semua <p> di seluruh halaman
      3. Last resort: get_text() seluruh <body> bersih dari tag
    """
    try:
        response = requests.get(url, headers=HEADERS, timeout=15)
        if response.status_code != 200:
            return None

        soup = BeautifulSoup(response.content, 'html.parser')

        # Hapus elemen non-konten (nav, header, footer, script, style, ads)
        for tag in soup(['script', 'style', 'noscript', 'nav', 'header',
                         'footer', 'aside', 'iframe', 'figure']):
            tag.decompose()

        # ── Prioritas 1: div.detail_text (body artikel CNN Indonesia) ──────
        content_div = (
            soup.find('div', class_='detail_text') or
            soup.find('div', class_=lambda c: c and 'detail_text' in c) or
            soup.find('div', class_=lambda c: c and 'article-body' in c) or
            soup.find('article')
        )

        if content_div:
            # Ambil semua teks di dalam container tersebut
            paragraphs = content_div.find_all(['p', 'h1', 'h2', 'h3', 'li'])
            text = '\n'.join(
                p.get_text(separator=' ', strip=True)
                for p in paragraphs
                if p.get_text(strip=True)
            )
            if text:
                return text

        # ── Prioritas 2: semua <p> di halaman ──────────────────────────────
        paragraphs = soup.find_all('p')
        text = '\n'.join(
            p.get_text(separator=' ', strip=True)
            for p in paragraphs
            if p.get_text(strip=True)
        )
        if text:
            return text

        # ── Prioritas 3 (last resort): seluruh body ─────────────────────────
        body = soup.find('body')
        if body:
            return re.sub(r'\n{3,}', '\n\n', body.get_text(separator='\n', strip=True))

        return None

    except Exception as e:
        return None


# ── Loop scraping semua link ──────────────────────────────────────────────────
if 'Link' not in links_df.columns:
    raise ValueError("Kolom 'Link' tidak ditemukan di CSV!")

urls = links_df['Link'].tolist()
contents = []

for i, url in enumerate(urls, 1):
    print(f'[{i:>3}/{len(urls)}] Scraping... {url[:80]}')
    content = scrape_content(url)
    contents.append(content)
    time.sleep(1)   # jeda sopan agar tidak diblok server

# Tambahkan kolom 'content' ke dataframe asli
df_article = links_df.copy()
df_article['content'] = contents

# Simpan versi mentah dengan kolom content
df_article.to_csv('cnn_with_content.csv', index=False, encoding='utf-8-sig')

print(f'\n✅ Selesai! {df_article["content"].notna().sum()}/{len(df_article)} artikel berhasil discrape.')
print(f'💾 Disimpan ke cnn_with_content.csv')
df_article.head(3)

[  1/99] Scraping... https://www.cnnindonesia.com/internasional/20260428200911-120-1353182/isi-dokume
[  2/99] Scraping... https://www.cnnindonesia.com/internasional/20260428135252-120-1353013/tanpa-ali-
[  3/99] Scraping... https://www.cnnindonesia.com/internasional/20260301044904-134-1332937/trump-konf
[  4/99] Scraping... https://www.cnnindonesia.com/internasional/20260501153618-134-1354171/trump-bing
[  5/99] Scraping... https://www.cnnindonesia.com/internasional/20260420111520-120-1349957/kenapa-ira
[  6/99] Scraping... https://www.cnnindonesia.com/internasional/20260304191525-120-1334389/mojtaba-kh
[  7/99] Scraping... https://www.cnnindonesia.com/internasional/20260301090739-120-1332969/waktu-terb
[  8/99] Scraping... https://www.cnnindonesia.com/internasional/20260309044622-120-1335708/tok-anak-a
[  9/99] Scraping... https://www.cnnindonesia.com/internasional/20260301174003-120-1333089/hamas-ucap
[ 10/99] Scraping... https://www.cnnindonesia.com/internasional/20260305065848-120-1334462/prabowo-ki
[ 11/99] Scraping... https://www.cnnindonesia.com/internasional/20260304192416-120-1334390/pemakaman-
[ 12/99] Scraping... https://www.cnnindonesia.com/internasional/20260304161927-120-1334325/israel-anc
[ 13/99] Scraping... https://www.cnnindonesia.com/internasional/20260301035703-120-1332929/netanyahu-
[ 14/99] Scraping... https://www.cnnindonesia.com/internasional/20260308175536-120-1335651/dewan-ulam
[ 15/99] Scraping... https://www.cnnindonesia.com/internasional/20260301113942-120-1333012/iran-mulai
[ 16/99] Scraping... https://www.cnnindonesia.com/internasional/20260304040218-120-1334038/ayatollah-
[ 17/99] Scraping... https://www.cnnindonesia.com/internasional/20260301134636-120-1333046/iran-tudin
[ 18/99] Scraping... https://www.cnnindonesia.com/internasional/20260301104905-120-1333003/raungan-ta
[ 19/99] Scraping... https://www.cnnindonesia.com/internasional/20260301094313-120-1332984/garda-revo
[ 20/99] Scraping... https://www.cnnindonesia.com/internasional/20260302150421-120-1333432/siapa-ali-
[ 21/99] Scraping... https://www.cnnindonesia.com/internasional/20260117210044-120-1318038/khamenei-t
[ 22/99] Scraping... https://www.cnnindonesia.com/nasional/20260303180218-32-1333939/megawati-kirim-s
[ 23/99] Scraping... https://www.cnnindonesia.com/internasional/20260301165228-120-1333083/presiden-i
[ 24/99] Scraping... https://www.cnnindonesia.com/internasional/20260301125649-134-1333040/iran-mau-b
[ 25/99] Scraping... https://www.cnnindonesia.com/internasional/20260301213329-113-1333152/9-orang-te
[ 26/99] Scraping... https://www.cnnindonesia.com/internasional/20250626193304-120-1244289/ali-khamen
[ 27/99] Scraping... https://www.cnnindonesia.com/internasional/20250625203532-120-1243871/ali-khamen
[ 28/99] Scraping... https://www.cnnindonesia.com/internasional/20250625162113-120-1243783/ali-khamen
[ 29/99] Scraping... https://www.cnnindonesia.com/internasional/20250618200938-120-1241225/israel-kem
[ 30/99] Scraping... https://www.cnnindonesia.com/internasional/20250622091650-120-1242393/as-serang-
[ 31/99] Scraping... https://www.cnnindonesia.com/internasional/20250628052235-134-1244558/trump-klai
[ 32/99] Scraping... https://www.cnnindonesia.com/internasional/20250616071256-120-1240052/perang-isr
[ 33/99] Scraping... https://www.cnnindonesia.com/hiburan/20250711154811-234-1249666/5-fakta-misteri-
[ 34/99] Scraping... https://www.cnnindonesia.com/internasional/20250626184532-120-1244264/ali-khamen
[ 35/99] Scraping... https://www.cnnindonesia.com/internasional/20260430175901-120-1353961/muncul-dar
[ 36/99] Scraping... https://www.cnnindonesia.com/internasional/20260430203434-120-1353991/kenapa-pem
[ 37/99] Scraping... https://www.cnnindonesia.com/internasional/20260430195444-120-1353977/pemimpin-t
[ 38/99] Scraping... https://www.cnnindonesia.com/internasional/20260429143956-120-1353453/trump-koar
[ 39/99] Scraping... https://www.cnnindonesia.com/internasional/20260301120927-120-1333020/petinggi-i
[ 40/99] Scraping... https://www.cnnindonesia.com/internasional/20260301121938-120-1333026/khamenei-t
[ 41/99] Scraping... https://www.cnnindonesia.com/internasional/20240815153715-120-1133453/pemimpin-t
[ 42/99] Scraping... https://www.cnnindonesia.com/nasional/20260427124457-20-1352524/dua-jemaah-haji-
[ 43/99] Scraping... https://www.cnnindonesia.com/internasional/20260301094139-120-1332983/siapa-peng
[ 44/99] Scraping... https://www.cnnindonesia.com/internasional/20240801153215-120-1128133/penyataan-
[ 45/99] Scraping... https://www.cnnindonesia.com/internasional/20260301083937-120-1332966/media-iran
[ 46/99] Scraping... https://www.cnnindonesia.com/internasional/20260303145726-120-1333868/iran-sebut
[ 47/99] Scraping... https://www.cnnindonesia.com/internasional/20260301060829-120-1332943/akun-resmi
[ 48/99] Scraping... https://www.cnnindonesia.com/internasional/20260302213153-120-1333596/khamenei-t
[ 49/99] Scraping... https://www.cnnindonesia.com/internasional/20260301100418-120-1332986/garda-revo
[ 50/99] Scraping... https://www.cnnindonesia.com/internasional/20260303100712-120-1333694/istri-kham
[ 51/99] Scraping... https://www.cnnindonesia.com/internasional/20260301152701-120-1333071/iran-sebut
[ 52/99] Scraping... https://www.cnnindonesia.com/internasional/20240801071732-120-1127878/khamenei-p
[ 53/99] Scraping... https://www.cnnindonesia.com/internasional/20260304135109-120-1334240/iran-gelar
[ 54/99] Scraping... https://www.cnnindonesia.com/internasional/20260301092122-120-1332970/khamenei-t
[ 55/99] Scraping... https://www.cnnindonesia.com/internasional/20260317214235-120-1339204/netanyahu-
[ 56/99] Scraping... https://www.cnnindonesia.com/internasional/20260313204832-120-1337888/as-klaim-m
[ 57/99] Scraping... https://www.cnnindonesia.com/internasional/20260301151535-120-1333069/khamenei-m
[ 58/99] Scraping... https://www.cnnindonesia.com/internasional/20260301043320-120-1332934/media-iran
[ 59/99] Scraping... https://www.cnnindonesia.com/internasional/20260302125924-120-1333355/pengganti-
[ 60/99] Scraping... https://www.cnnindonesia.com/internasional/20260301070525-120-1332950/korban-tew
[ 61/99] Scraping... https://www.cnnindonesia.com/internasional/20260301140746-120-1333051/menteri-pe
[ 62/99] Scraping... https://www.cnnindonesia.com/internasional/20260301044620-120-1332935/selain-kha
[ 63/99] Scraping... https://www.cnnindonesia.com/internasional/20260318113949-120-1339311/iran-balas
[ 64/99] Scraping... https://www.cnnindonesia.com/internasional/20260420153112-120-1350052/pejabat-ir
[ 65/99] Scraping... https://www.cnnindonesia.com/internasional/20260303165821-120-1333919/israel-gem
[ 66/99] Scraping... https://www.cnnindonesia.com/internasional/20260301064953-120-1332948/trump-bers
[ 67/99] Scraping... https://www.cnnindonesia.com/internasional/20260301110206-120-1333004/iran-konfi
[ 68/99] Scraping... https://www.cnnindonesia.com/internasional/20260312133650-113-1337237/putri-kim-
[ 69/99] Scraping... https://www.cnnindonesia.com/internasional/20260302143922-134-1333405/trump-pame
[ 70/99] Scraping... https://www.cnnindonesia.com/internasional/20260314093953-134-1337945/as-tawarka
[ 71/99] Scraping... https://www.cnnindonesia.com/internasional/20260301115401-120-1333013/trump-sebu
[ 72/99] Scraping... https://www.cnnindonesia.com/internasional/20260301064018-134-1332947/reaksi-rus
[ 73/99] Scraping... https://www.cnnindonesia.com/internasional/20260302121959-120-1333334/trump-pame
[ 74/99] Scraping... https://www.cnnindonesia.com/internasional/20260301183909-134-1333099/paus-henti
[ 75/99] Scraping... https://www.cnnindonesia.com/internasional/20260312084546-120-1337094/trump-pusi
[ 76/99] Scraping... https://www.cnnindonesia.com/internasional/20260301134433-120-1333044/ribuan-war
[ 77/99] Scraping... https://www.cnnindonesia.com/internasional/20260311182310-120-1336961/aset-ekono
[ 78/99] Scraping... https://www.cnnindonesia.com/internasional/20260301100609-120-1332987/akhir-trag
[ 79/99] Scraping... https://www.cnnindonesia.com/internasional/20260311190231-120-1336968/mojtaba-kh
[ 80/99] Scraping... https://www.cnnindonesia.com/internasional/20260302001236-106-1333173/anwar-ibra
[ 81/99] Scraping... https://www.cnnindonesia.com/internasional/20260118170202-120-1318216/demo-anti-
[ 82/99] Scraping... https://www.cnnindonesia.com/internasional/20260424101505-120-1351505/pesan-terb
[ 83/99] Scraping... https://www.cnnindonesia.com/internasional/20260331193617-120-1343079/satu-lagi-
[ 84/99] Scraping... https://www.cnnindonesia.com/internasional/20260301150044-120-1333067/5-nama-cal
[ 85/99] Scraping... https://www.cnnindonesia.com/internasional/20260302114417-120-1333308/pejabat-ge
[ 86/99] Scraping... https://www.cnnindonesia.com/internasional/20260303090729-134-1333676/as-akui-se
[ 87/99] Scraping... https://www.cnnindonesia.com/internasional/20260318143727-120-1339372/iran-eksek
[ 88/99] Scraping... https://www.cnnindonesia.com/hiburan/20260304105640-234-1334133/konflik-timur-te
[ 89/99] Scraping... https://www.cnnindonesia.com/hiburan/20260306135505-234-1335057/berhasil-pulang-
[ 90/99] Scraping... https://www.cnnindonesia.com/hiburan/20260305094015-234-1334529/imbas-perang-gad
[ 91/99] Scraping... https://www.cnnindonesia.com/internasional/20260319081039-120-1339528/iran-konfi
[ 92/99] Scraping... https://www.cnnindonesia.com/nasional/20260311062746-32-1336620/ditemui-dubes-ir
[ 93/99] Scraping... https://www.cnnindonesia.com/internasional/20260302211607-120-1333593/daftar-neg
[ 94/99] Scraping... https://www.cnnindonesia.com/internasional/20251124074155-120-1298706/intelijen-
[ 95/99] Scraping... https://www.cnnindonesia.com/internasional/20260316074820-120-1338420/dirumorkan
[ 96/99] Scraping... https://www.cnnindonesia.com/internasional/20260309122829-120-1335874/kontrovers
[ 97/99] Scraping... https://www.cnnindonesia.com/internasional/20260119102639-120-1318375/jumlah-kor
[ 98/99] Scraping... https://www.cnnindonesia.com/internasional/20260119081450-120-1318308/pemimpin-t
[ 99/99] Scraping... https://www.cnnindonesia.com/internasional/20260423123508-113-1351159/jamu-utusa

✅ Selesai! 99/99 artikel berhasil discrape.
💾 Disimpan ke cnn_with_content.csv

,Judul,Link,Kategori,Tanggal_Upload,content
0,Isi Dokumen Fatwa Ali Khamenei Mengharamkan Bo...,https://www.cnnindonesia.com/internasional/202...,Internasional,3 hari yang lalu,Isi Dokumen Fatwa Ali Khamenei Mengharamkan Bo...
1,"Tanpa Ali Khamenei, Israel Justru Ketar-ketir ...",https://www.cnnindonesia.com/internasional/202...,Internasional,4 hari yang lalu,"Tanpa Ali Khamenei, Israel Justru Ketar-ketir ..."
2,Trump Konfirmasi Kematian Pemimpin Tertinggi I...,https://www.cnnindonesia.com/internasional/202...,Internasional,2 bulan yang lalu,Trump Konfirmasi Kematian Pemimpin Tertinggi I...

In [8]:
from google.colab import files
files.download('cnn_with_content.csv')